baseURL = "https://katiep.github.io/urban_canopy/"
languageCode = "en-us"
Title = "Urban Canopy"
title = "Urban Canopy"
summaryLength = 25
paginate = 1000
enableEmoji = true
publishDir = "./docs"

[markup.goldmark.renderer]
  unsafe= true
